name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request: # Autolabel PR's
    types: [opened, labeled, unlabeled, synchronize]
  pull_request_target: # Autolabel PR's from forks
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  update_release_draft:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
